name: Run Prediction Model

on:
  schedule:
    # Run daily at 12 PM (UTC)
    - cron: '0 12 * * *'
  workflow_dispatch:
    # Allow manual trigger
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the prediction model
      - name: Run prediction model
        run: |
          python predict_model.py
