name: Run Prediction Model

permissions:
  contents: write  # Allow write access for the action to push changes

on:
  schedule:
    # Run daily at 17 (UTC)
    - cron: '0 17 * * *'
  workflow_dispatch:
    # Allow manual trigger
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.11.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the script to get data (get_data.py)
      - name: Get data
        run: |
          python get_data.py

      # Step 5: Commit and push the fetched data
      - name: Commit and push the fetched data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Updated fetched data"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

      # Step 6: Run the prediction model (predict_model.py)
      - name: Run prediction model
        run: |
          python predict_model.py
